### ISSUE TITLE
Ability to run healthcheck when endpoint is secured with Basic Auth

### ISSUE THREAD

**Issue by gheibia** [lawrencegripper/traefik-appinsights-watchdog#22]
As soon as I secure Traefik's 8080 endpoint through which APIs and dashboard are served, the healthcheck fails with 401 (naturally). Is it worth adding a couple of configuration parameters that allow passing credentials to be used when making the GET healthcheck request?

I'll be happy to provide a PR.

**Comment by lawrencegripper** [comment]
Sure, I'd be more than happy to accept a PR that adds some optional params for basic auth. Thanks for the offer

**Comment by lawrencegripper** [comment]
Great work, thanks for picking up this one! I'll close this issue off now.
