### ISSUE TITLE
Routing check fails for Watchdog, which isn't registered in the Traefik dashboard

### ISSUE THREAD

**Issue by paul-mcgrath** [lawrencegripper/traefik-appinsights-watchdog#26]
Hi there,

I noticed that our Watchdog's health check is working correctly, but it fails the routing check with a 404.

When I try and go to the registered route `/TraefikType/Watchdog` it doesn't seem to exist, and is not registered on the dashboard.

Any idea why it might work for health, but not for route registration or route checking?

**Comment by paul-mcgrath** [comment]
So the fix was to update the enablement key for my version of Traefik.

The snippet in my service manifest was:             
`<Label Key="traefik.expose">true</Label>`

But needed to be:
`<Label Key="traefik.enable">true</Label>`

**Comment by lawrencegripper** [comment]
Thanks Paul, sorry I wasn't able to pick this up sooner. Did this happen when updating traefik to a newer version or is there an outdated bit of documentation somewhere I can fix up?

**Comment by paul-mcgrath** [comment]
Hi Lawrence, the Watchdog manifest template [here](https://github.com/jjcollinge/traefik-on-service-fabric/blob/fd4bee6b51c5d417920235ed4ae9a5981592976b/Traefik/ApplicationPackageRoot/Watchdog/ServiceManifest.xml#L10) has `expose` but newer versions of Traefik use `enable`.

There is a warning at the top of the Traefik on Service Fabric readme that this label is changing, so I was
unsure about opening a PR to update it.

**Comment by lawrencegripper** [comment]
Thanks! Yeah lets open up a PR to update that as the change in label shipped some time ago and it's likely to affect others. Happy to accept a PR if you wanted to do a quick edit?

**Comment by paul-mcgrath** [comment]
No problem, just opened a PR [here](https://github.com/jjcollinge/traefik-on-service-fabric/pull/83).

**Comment by lawrencegripper** [comment]
Awesome thanks!
